# -*- coding: utf-8 -*-
"""binomial_option.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aglx1ZZMWn_hnfaEpnBjWXjC11eH0zgA
"""

import math

class BinomialOption:
    """
    Binomial tree option pricing model supporting European and American options.
    """

    def __init__(self, S0, K, r, sigma, T, n, option_type='put', american=True):
        """
        Parameters:
            S0 : float - Initial stock price
            K : float - Strike price
            r : float - Risk-free interest rate
            sigma : float - Volatility
            T : float - Time to maturity (in years)
            n : int - Number of time steps
            option_type : str - 'call' or 'put'
            american : bool - True for American option, False for European
        """
        self.S0 = S0
        self.K = K
        self.r = r
        self.sigma = sigma
        self.T = T
        self.n = n
        self.option_type = option_type.lower()
        self.american = american

        # derived parameters
        self.dt = T / n
        self.u = math.exp(sigma * math.sqrt(self.dt))
        self.d = 1 / self.u
        self.R = math.exp(r * self.dt)
        self.p = (self.R - self.d) / (self.u - self.d)

    def _payoff(self, S):
        """Return payoff for given stock price S."""
        if self.option_type == 'call':
            return max(S - self.K, 0.0)
        elif self.option_type == 'put':
            return max(self.K - S, 0.0)
        else:
            raise ValueError("option_type must be 'call' or 'put'")

    def price(self):
        """Return the option price using backward induction."""
        # Final prices at maturity
        prices = [self.S0 * (self.u ** j) * (self.d ** (self.n - j)) for j in range(self.n + 1)]
        values = [self._payoff(S) for S in prices]

        # Backward induction
        for i in range(self.n - 1, -1, -1):
            new_values = []
            for j in range(i + 1):
                hold = (self.p * values[j + 1] + (1 - self.p) * values[j]) / self.R
                if self.american:
                    S_ij = self.S0 * (self.u ** j) * (self.d ** (i - j))
                    exercise = self._payoff(S_ij)
                    new_values.append(max(hold, exercise))
                else:
                    new_values.append(hold)
            values = new_values

        return values[0]