# -*- coding: utf-8 -*-
"""example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aMuGviaCwi3rEnVc82BhOXgaN1knn621
"""

from binomial_option import BinomialOption

if __name__ == "__main__":
    # American Put Option
    put_option = BinomialOption(S0=100, K=100, r=0.05, sigma=0.2, T=1, n=100, option_type='put', american=True)
    print(f"American Put Option Price: {put_option.price():.4f}")

    # European Call Option
    call_option = BinomialOption(S0=100, K=100, r=0.05, sigma=0.2, T=1, n=100, option_type='call', american=False)
    print(f"European Call Option Price: {call_option.price():.4f}")

    # European Put Option
    put_option = BinomialOption(S0=100, K=100, r=0.05, sigma=0.2, T=1, n=100, option_type='put', american=False)
    print(f"European Put Option Price: {put_option.price():.4f}")